# Generated by Django 3.2.5 on 2021-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.TextField()),
                ('eventdesc', models.TextField(blank=True, null=True)),
                ('eventDate', models.DateTimeField(blank=True, null=True)),
                ('eventLocation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
